project1/wiki/encyclopedia/urls.py
from django.urls import path

from . import views

app_name= "encyclopedia"
urlpatterns = [
    path("", views.index, name="index"),
    path("wiki/<str:title>/", views.dynamic_wiki, name="wiki"),
    path("add/", views.add, name="add"),
    path("random/", views.random_wiki, name="random"),
    path("wiki/<str:title>/edit", views.edit, name="edit"),
]

project1/wiki/wiki/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("encyclopedia.urls"))
]

project1/wiki/encyclopedia/models.py
from django.db import models

# Create your models here.

project1/wiki/encyclopedia/views.py
import random
import re
from django import forms
from django.http import Http404
from django.shortcuts import redirect, render
import markdown

from . import util

class NewWikiForm(forms.Form):
    title = forms.CharField(label="", widget=forms.TextInput(attrs={'placeholder': 'Title'}))
    content = forms.CharField(label="", widget=forms.Textarea(attrs={'placeholder': 'Content'}))

class EditWikiForm(forms.Form):
    content = forms.CharField(label="", widget=forms.Textarea(attrs={'placeholder': 'Content'}))

def index(request):
    q = request.GET.get('q')
    if (q):
        entries = util.list_entries()

        return render(request, "encyclopedia/search.html", {
            "q": q,
            "entries": [entry for entry in entries if q.lower() in entry.lower()]
        })

    return render(request, "encyclopedia/index.html", {
        "entries": util.list_entries()
    })

def dynamic_wiki(request, title):
    entry = util.get_entry(title)
    
    if (entry):
        content = markdown.markdown(util.get_entry(title))
        
        return render(request, 'encyclopedia/wiki.html', {
            "title": title,
            "content": content
        })
    
    entries = util.list_entries()
    
    return render(request, "encyclopedia/wiki_not_found.html", {
        "q": title,
        "entries": [entry for entry in entries if title.lower() in entry.lower()]
    })

def add(request):
    if (request.method == "GET"):
        return render(request, "encyclopedia/add.html", {
            "form": NewWikiForm()
        })
    elif (request.method == "POST"):
        form = NewWikiForm(request.POST)
        if form.is_valid():
            form_data = form.cleaned_data
            util.save_entry(form_data["title"], form_data["content"])
            return redirect('encyclopedia:index')
        
        return render(request, "encyclopedia/add.html", {
            "form": form
        })
    
def random_wiki(request):
    return redirect('encyclopedia:wiki', title=random.choice(util.list_entries()))

def edit(request, title):
    data = util.get_entry(title).split('\n', 1)
    content = data[1].strip()
    title = re.search(r'^#\s*(.+)$', data[0]).group(1).strip()

    if (request.method == "GET"):
        form = EditWikiForm({
            "content": content,
        })

        return render(request, "encyclopedia/edit.html", {
            "title": title,
            "form": form,
        })
    elif (request.method == "POST"):
        form = EditWikiForm(request.POST)
        if form.is_valid():
            form_data = form.cleaned_data
            util.save_entry(title, form_data["content"])
            return redirect('encyclopedia:wiki', title=title)
        
        return render(request, "encyclopedia/edit.html", {
            "title": title,
            "form": form,
        })

project1/wiki/encyclopedia/templates/encyclopedia/add.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>Create new Wiki</h1>

    <form action="{% url 'encyclopedia:add' %}" method="post">
        {% csrf_token %} 
        {{ form }}
        <input type="submit" value="Create">
    </form>

{% endblock %}

project1/wiki/encyclopedia/templates/encyclopedia/edit.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>Editar {{ title }}</h1>
    <form action="{% url 'encyclopedia:edit' title=title %}" method="post">
        {% csrf_token %} 
        {{ form }}
        <input type="submit" value="Edit">
        <!-- <a href="{% url 'encyclopedia:wiki' title=title %}">Voltar</a> -->
    </form>

{% endblock %}

project1/wiki/encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>All Pages</h1>

    <ul>
        {% for entry in entries %}
            <li><a href="{% url 'encyclopedia:wiki' title=entry %}">{{ entry }}</a></li>
        {% empty %}
            <li>No Wikis.</li>
        {% endfor %}
    </ul>

{% endblock %}

project1/wiki/encyclopedia/templates/encyclopedia/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'encyclopedia/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        <div class="row">
            <div class="sidebar col-lg-2 col-md-3">
                <h2>Wiki</h2>
                <form action="{% url 'encyclopedia:index' %}">
                    <input class="search" type="text" name="q" placeholder="Search Encyclopedia">
                </form>
                <div>
                    <a href="{% url 'encyclopedia:index' %}">Home</a>
                </div>
                <div>
                    <a href="{% url 'encyclopedia:add' %}">Create New</a>
                </div>
                <div>
                    <a href="{% url 'encyclopedia:random' %}">Random Page</a>
                </div>
                {% block nav %}
                {% endblock %}
            </div>
            <div class="main col-lg-10 col-md-9">
                {% block body %}
                {% endblock %}
            </div>
        </div>

    </body>
</html>

project1/wiki/encyclopedia/templates/encyclopedia/search.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>Results for "{{ q }}"</h1>
    
    <ul>
        {% for entry in entries %}
            <li><a href="{% url 'encyclopedia:wiki' title=entry %}">{{ entry }}</a></li>
        {% empty %}
            <li>No Wikis found.</li>
        {% endfor %}
    </ul>

{% endblock %}

project1/wiki/encyclopedia/templates/encyclopedia/wiki.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}

    {{ content |safe }}

    <a href="{% url 'encyclopedia:edit' title=title %}">Edit</a>

{% endblock %}

project1/wiki/encyclopedia/templates/encyclopedia/wiki_not_found.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>Wiki "{{ q }}" not found</h1>
    
    {% if entries %}
    <p>Perhaps you meant one of these:</p>
    <ul>
        {% for entry in entries %}
            <li><a href="{% url 'encyclopedia:wiki' title=entry %}">{{ entry }}</a></li>
        {% endfor %}
    </ul>
    {% else %}
        <p>No similar Wiki found.</p>
    {% endif %}

{% endblock %}